# Site settings
title: Weave Flux
description: Weave Flux
email: help@weave.works
baseurl: ""
url: "http://weave.works/flux/"
twitter_username: weavenetwork
github_username:  weaveworks

# Build settings
markdown: kramdown
#permalink: pretty
exclude: ["README.md", "Gemfile", "Gemfile.lock"]

kramdown:
        input: GFM
        syntax_highlighter: rouge
        hard_wrap: false
